---
title: '26 July 2018 report '
output:
  html_document:
    df_print: paged
  pdf_document: default
---

Report for 26 July data.


```{r setup, include=FALSE}
library(stringi)
knitr::opts_chunk$set(echo = TRUE, tidy=TRUE,cache = TRUE, cache.lazy = FALSE)
knitr::opts_knit$set(root.dir="../")

```

```{r setup2, include=FALSE}

source("../util/apply_local_settings.R")
apply_local_settings()
knitr::opts_chunk$set(cache.path = paste0(localsettings$data.dir,"knitrcache"),
                      echo=FALSE)


```


## EV and RL correlations 


```{r ev_rl_correlations_setup, include=FALSE}
source("stanlba/lba_rl_joint_setup.R")
source("stanlba/singlelevelmodel/single_level_model_summarize_fast.R")
source("stanlba/singlelevelmodel/lba_rl_joint_v2_evaluate_functions.R")
source("stanlba/singlelevelmodel/lba_rl_joint_v1_functions.R")
source("stanlba/singlelevelmodel/lba_rl_joint_v7_functions.R")
source("stanlba/singlelevelmodel/lba_rl_joint_v10_functions.R")

regions<-get_dmn_regions()
#what we really wanna do is extract the sigmas
Sigma_dims<-25
rpe_covarvec<-paste0("Sigma[",1:Sigma_dims[1],",",1,"]")
rpe_covarvec_df<-paste0("Sigma.",1:Sigma_dims[1],".",1,".")
library(rstan)


lba_rl_version<-"rl_joint_20180723_1"

DeltaThetaLabels=paste0("con_",get_dmn_regions())

library(rstan)



model_rl_joint_v9<-single_level_model_summarize_fast(
  single_run_dir=paste0(localsettings$data.dir,"lba_rl"),
  model_version=lba_rl_version,
  model_filename="rl_single_exp_joint_v9",
  model_subversion="")

```


### For a pure RL Model

```{r ev_rl_correlations, include=FALSE}

```

### For an RL+LBA Model

```{r ev_rl_lba_correlations_setup, include=FALSE}

model_lba_rl_joint_v13<-single_level_model_summarize_fast(
  single_run_dir=paste0(localsettings$data.dir,"lba_rl"),
  model_version="joint_20180723_1",
  model_filename="lba_rl_single_exp_joint_v13",
  model_subversion="")

source("stanlba/singlelevelmodel/empirical_correlations_estimate.R")
neural_trial_data<-merge_with_neural_data(model_lba_rl_joint_v13$results_summary_dt)
```

```{r ev_rl_lba_correlations_display, echo=FALSE, fig.width=12,fig.height=12}

ggplot(neural_trial_data[(sid %% 5)==0 ],aes(trial_expected_val,con_ROI_Left.Accumbens.area,color=as.factor(presentation_n)))+geom_point()+
  facet_wrap(~interaction(sid,rid,motivation),scales = "free")+
  labs(title="L Accumbens Activity by EV for each run", x="EV",color="Presentation Number")


ggplot(neural_trial_data[(sid %% 5)==0 ],aes(run_pred_err_c2,con_ROI_Left.Accumbens.area,color=as.factor(presentation_n)))+geom_point()+
  facet_wrap(~interaction(sid,rid,motivation),scales = "free")+
  labs(title="L Accumbens Activity by RPE for each run", x="RPE",color="Presentation Number")

```

```{r ev_rl_lba_correlations_display_abs, echo=FALSE, fig.width=12,fig.height=12}

ggplot(neural_trial_data[(sid %% 5)==0],aes(run_pred_err_c2_abs,con_ROI_Left.Accumbens.area,color=as.factor(presentation_n)))+geom_point()+
  facet_wrap(~interaction(sid,rid,motivation),scales = "free")+
  labs(title="L Accumbens Activity by Abs(RPE) for each run", x="RPE",color="Presentation Number")

ggplot(neural_trial_data[(sid %% 5)==0],aes(run_pred_err_c2_abs,con_ROI_Right.Accumbens.area,color=as.factor(presentation_n)))+geom_point()+
  facet_wrap(~interaction(sid,rid,motivation),scales = "free")+
  labs(title="R Accumbens Activity by Abs(RPE) for each run", x="RPE",color="Presentation Number")

```

#simple RL model

```{r ev_rl_correlations_setup2, echo=FALSE, fig.width=12,fig.height=12}
neural_trial_data<-merge_with_neural_data(model_rl_joint_v9$results_summary_dt)

```

## EV


```{r rl_lba_correlations_display_ev, echo=FALSE, fig.width=12,fig.height=12}

ggplot(neural_trial_data[(sid %% 5)==0 ],aes(trial_expected_val,con_ROI_Left.Accumbens.area,color=as.factor(presentation_n)))+geom_point()+
  facet_wrap(~interaction(sid,rid,motivation),scales = "free")+
  labs(title="L Accumbens Activity by EV for each run", x="EV",color="Presentation Number")
```

## RPE

```{r rl_lba_correlations_display_rpe, echo=FALSE, fig.width=12,fig.height=12}
ggplot(neural_trial_data[(sid %% 5)==0 ],aes(run_pred_err_c2,con_ROI_Left.Accumbens.area,color=as.factor(presentation_n)))+geom_point()+
  facet_wrap(~interaction(sid,rid,motivation),scales = "free")+
  labs(title="L Accumbens Activity by RPE for each run", x="RPE",color="Presentation Number")
```


